# Generated by Django 5.1.4 on 2026-04-15 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('language', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('description', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('trailer_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField()),
                ('total_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'screens',
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
            ],
            options={
                'db_table': 'theatres',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vip_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.screen')),
            ],
            options={
                'db_table': 'shows',
                'ordering': ['show_time'],
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theatre'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP')], default='NORMAL', max_length=10)),
                ('row_name', models.CharField(default='A', max_length=5)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen')),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['row_name', 'seat_number'],
                'unique_together': {('screen', 'seat_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('theatre', 'screen_number')},
        ),
    ]
